cargo publish fixes

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,17 +10,18 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        steps:
-          - name: Release
-            run: gh release create "$(grep '^version =' Cargo.toml | cut -d' ' -f3 | tr -d '\"')" || echo "Release failed, continuing..."
+      - name: Checkout
+        uses: actions/checkout@v4
 
-          - name: Publish
-            run: cargo publish --allow-dirty || echo "Cargo publish failed, continuing..."
-            env:
-              CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
+      - name: Release
+        run: gh release create "$(grep '^version =' Cargo.toml | cut -d' ' -f3 | tr -d '\"')" || echo "Release failed, continuing..."
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Publish
+        run: cargo publish --allow-dirty || echo "Cargo publish failed, continuing..."
+        env:
+          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
 
   build:
     runs-on: ${{ matrix.runner }}
