added cargo publish task back

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,7 +13,14 @@ jobs:
       - uses: actions/checkout@v4
       - env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: gh release create "$(grep '^version =' Cargo.toml | cut -d' ' -f3 | tr -d '\"')"
+        steps:
+          - name: Release
+            run: gh release create "$(grep '^version =' Cargo.toml | cut -d' ' -f3 | tr -d '\"')" || echo "Release failed, continuing..."
+
+          - name: Publish
+            run: cargo publish --allow-dirty || echo "Cargo publish failed, continuing..."
+            env:
+              CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
 
   build:
     runs-on: ${{ matrix.runner }}
